# Generated by Django 2.1.7 on 2019-07-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonorprofile',
            name='license',
        ),
    ]
