# Generated by Django 2.1.7 on 2019-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonor', '0002_remove_blooddonorprofile_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonorprofile',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
