# Generated by Django 2.1.7 on 2019-08-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonor', '0004_auto_20190728_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonorprofile',
            name='qrcode',
            field=models.ImageField(default=None, upload_to='qrcodes/'),
            preserve_default=False,
        ),
    ]
