# Generated by Django 2.1.7 on 2019-08-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonor', '0005_blooddonorprofile_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonorprofile',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='qrcodes/'),
        ),
    ]
