# Generated by Django 2.1.7 on 2019-08-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonor', '0006_auto_20190803_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonorprofile',
            name='qrcode',
        ),
    ]
