# Generated by Django 2.1.7 on 2019-08-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonor', '0010_blooddonorprofile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonorprofile',
            name='blood_report',
            field=models.FileField(null=True, upload_to='bloodreports/'),
        ),
    ]
