# Generated by Django 2.1.7 on 2019-07-28 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20190727_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='hospital.User1'),
        ),
    ]
