# Generated by Django 2.1.7 on 2019-08-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20190728_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='hospitalprofiles/'),
        ),
    ]
